"""
This type stub file was generated by pyright.
"""

class LangProfile:
    MINIMUM_FREQ = ...
    LESS_FREQ_RATIO = ...
    ROMAN_CHAR_RE = ...
    ROMAN_SUBSTR_RE = ...
    def __init__(self, name=..., freq=..., n_words=...) -> None:
        ...
    
    def add(self, gram): # -> None:
        '''Add n-gram to profile.'''
        ...
    
    def omit_less_freq(self): # -> None:
        '''Eliminate below less frequency n-grams and noise Latin alphabets.'''
        ...
    
    def update(self, text): # -> None:
        '''Update the language profile with (fragmented) text.
        Extract n-grams from text and add their frequency into the profile.
        '''
        ...
    


