"""
This type stub file was generated by pyright.
"""

class Messages:
    MESSAGES_FILENAME = ...
    def __init__(self) -> None:
        ...
    
    def get_string(self, key):
        ...
    


_messages = ...
def get_string(key):
    ...

