"""
This type stub file was generated by pyright.
"""

class DetectorFactory:
    '''
    Language Detector Factory Class.

    This class manages an initialization and constructions of Detector.

    Before using language detection library,
    load profiles with DetectorFactory.load_profile(str)
    and set initialization parameters.

    When the language detection,
    construct Detector instance via DetectorFactory.create().
    See also Detector's sample code.
    '''
    seed = ...
    def __init__(self) -> None:
        ...
    
    def load_profile(self, profile_directory): # -> None:
        ...
    
    def load_json_profile(self, json_profiles): # -> None:
        ...
    
    def add_profile(self, profile, index, langsize): # -> None:
        ...
    
    def clear(self): # -> None:
        ...
    
    def create(self, alpha=...): # -> Detector:
        '''Construct Detector instance with smoothing parameter.'''
        ...
    
    def set_seed(self, seed): # -> None:
        ...
    
    def get_lang_list(self): # -> list[Any]:
        ...
    


PROFILES_DIRECTORY = ...
_factory = ...
def init_factory(): # -> None:
    ...

def detect(text): # -> Literal['unknown']:
    ...

def detect_langs(text): # -> list[Language]:
    ...

