"""
This type stub file was generated by pyright.
"""

_error_codes = ...
ErrorCode = ...
class LangDetectException(Exception):
    def __init__(self, code, message) -> None:
        ...
    
    def get_code(self): # -> Any:
        ...
    


