"""
This type stub file was generated by pyright.
"""

class Language:
    '''
    Language is to store the detected language.
    Detector.get_probabilities() returns a list of Languages.
    '''
    def __init__(self, lang, prob) -> None:
        ...
    
    def __repr__(self): # -> LiteralString | Literal['']:
        ...
    
    def __lt__(self, other) -> bool:
        ...
    


