"""
This type stub file was generated by pyright.
"""

destinations = ...
charset_map = ...
sectionchars = ...
specialchars = ...
PATTERN = ...
HYPERLINKS = ...
def remove_pict_groups(rtf_text): # -> LiteralString:
    """
    Remove all \\pict groups with binary data from the RTF text.
    If no binary-encoded \\pict groups are found, return the original text.
    See issue 58
    """
    ...

FONTTABLE = ...
def rtf_to_text(text, encoding=..., errors=...):
    """Converts the rtf text to plain text.

    Parameters
    ----------
    text : str
        The rtf text
    encoding : str
        Input encoding which is ignored if the rtf file contains an explicit codepage directive,
        as it is typically the case. Defaults to `cp1252` encoding as it the most commonly used.
    errors : str
        How to handle encoding errors. Default is "strict", which throws an error. Another
        option is "ignore" which, as the name says, ignores encoding errors.

    Returns
    -------
    str
        the converted rtf text as a python unicode string
    """
    ...

